export default [
  {
    id: 1,
    featured: true,
    slug: "wild-dog",
    title: "African Wild Dog",
    latin: "Lycaon pictus",
    order: "carnivora",
    suborder: "caniformia",
    superFamily: "",
    family: "canidae",
    subFamily: "",
    tribe: "",
    collective: ["pack"],
    weight: "17-25 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "60-75 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "30-40 cm",
    tailMale: "",
    tailFemale: "",
    length: "106-150 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "2.5 months",
    teats: "12-14",
    teeth: 42,
    photos: [
      {
        id: 1,
        title: "Wild Dog",
        description: "",
        imgURL: "../assets/images/animals/wild-dog.jpg",
        active: true
      }
    ]
  },
  {
    id: 2,
    featured: true,
    slug: "buffalo",
    title: "African Buffalo",
    latin: "Syncerus caffer",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "bovinae",
    tribe: "bovini",
    collective: ["obstinancy", "gang", "herd"],
    weight: "",
    weightMale: "700-800 kg",
    weightFemale: "550-750 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "1.4-1.6 m",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "70 cm",
    tailMale: "",
    tailFemale: "",
    length: "2.9 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "both genders",
    gestation: "340 days",
    teats: "4 inguinal",
    teeth: 32,
    photos: [
      {
        id: 1,
        title: "African Buffalo",
        description: "",
        imgURL: "../assets/images/animals/buffalo.jpg",
        active: true
      }
    ]
  },
  {
    id: 3,
    featured: true,
    slug: "elephant",
    title: "African Savannah Elephant",
    latin: "Loxodonta africana",
    order: "proboscidae",
    suborder: "",
    superFamily: "",
    family: "elephantidae",
    subFamily: "",
    tribe: "",
    collective: ["parade", "herd"],
    weight: "",
    weightMale: "5000-6200 kg",
    weightFemale: "2500-3500 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "",
    shoulderMale: "3.2-3.8 m",
    shoulderFemale: "2.4-3.4 m",
    tail: "1.5 m",
    tailMale: "",
    tailFemale: "",
    length: "",
    lengthMale: "7-9 m",
    lengthFemale: "6.5-8.5 m",
    horns: "",
    gestation: "22 months",
    teats: "2 pectoral",
    teeth: 28,
    photos: [
      {
        id: 1,
        title: "African Savannah Elephant",
        description: "",
        imgURL: "../assets/images/animals/elephant.jpg",
        active: true
      }
    ]
  },
  {
    id: 4,
    featured: true,
    slug: "baboon",
    title: "Chacma Baboon",
    latin: "Papio cynocephalus ursinus",
    order: "primata",
    suborder: "haplorhini",
    superFamily: "cercopithecoidea",
    family: "cercopithecidae",
    subFamily: "",
    tribe: "",
    collective: ["troop", "flange", "congress"],
    weight: "",
    weightMale: "27-45 kg",
    weightFemale: "12-20 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "",
    shoulderMale: "71 cm",
    shoulderFemale: "61 cm",
    tail: "",
    tailMale: "60-85 cm",
    tailFemale: "50-60 cm",
    length: "",
    lengthMale: "120-160 cm",
    lengthFemale: "100-120 cm",
    horns: "",
    gestation: "6 months",
    teats: "2 pectoral",
    teeth: 32,
    photos: [
      {
        id: 1,
        title: "Chacma Baboon",
        description: "",
        imgURL: "../assets/images/animals/baboon-01.jpg",
        active: true
      }
    ]
  },
  {
    id: 5,
    featured: true,
    slug: "cheetah",
    title: "Cheetah",
    latin: "Acinonyx jubatus",
    order: "carnivora",
    suborder: "feliformia",
    superFamily: "",
    family: "felidae",
    subFamily: "acinonychinae",
    tribe: "",
    collective: ["coalition"],
    weight: "",
    weightMale: "40-65 kg",
    weightFemale: "36-48 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "80 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "60-80 cm",
    tailMale: "",
    tailFemale: "",
    length: "",
    lengthMale: "1.8-2.1 m",
    lengthFemale: "1.6-2.1 m",
    horns: "",
    gestation: "3 months",
    teats: "5-6 pair abdominal/pectoral",
    teeth: 30,
    photos: [
      {
        id: 1,
        title: "Cheetah",
        description: "",
        imgURL: "../assets/images/animals/cheetah.jpg",
        active: true
      }
    ]
  },
  {
    id: 6,
    featured: true,
    featuredPhoto: "../assets/images/animals/giraffe.jpg",
    featuredTitle: "This is tallest of the mammal species.",
    slug: "giraffe",
    title: "Giraffe",
    latin: "Giraffa camelopardalis",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "giraffidae",
    subFamily: "",
    tribe: "",
    collective: ["tower", "journey", "group"],
    weight: "",
    weightMale: "970-1400 kg",
    weightFemale: "650-950 kg",
    height: "",
    heightMale: "3.9-5.5 m",
    heightFemale: "3.7-4.7 m",
    shoulder: "",
    shoulderMale: "2.5-3.5 m",
    shoulderFemale: "2-3 m",
    tail: "",
    tailMale: "95-150 cm",
    tailFemale: "70-150 cm",
    length: "",
    lengthMale: "120-160 cm",
    lengthFemale: "100-200 cm",
    horns: "",
    gestation: "15 months",
    teats: "4 inguinal",
    teeth: 32,
    photos: [
      {
        id: 1,
        title: "Giraffe",
        description: "Giraffe",
        imgURL: "../assets/images/animals/giraffe.jpg",
        active: true
      },
      {
        id: 2,
        title: "Giraffe",
        description: "Giraffe's tail closeup.",
        imgURL: "../assets/images/animals/giraffe-02.jpg",
        active: false
      }
    ]
  },
  {
    id: 7,
    featured: true,
    featuredPhoto: "../assets/images/animals/lion.jpg",
    featuredTitle: "This is the featured title text.",
    slug: "lion",
    title: "Lion",
    latin: "Panthera leo",
    order: "carnivora",
    suborder: "feliformia",
    superFamily: "",
    family: "felidae",
    subFamily: "pantherinae",
    tribe: "",
    collective: ["pride"],
    weight: "",
    weightMale: "150-225 kg",
    weightFemale: "110-160 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "",
    shoulderMale: "120 cm",
    shoulderFemale: "100 cm",
    tail: "100 cm",
    tailMale: "",
    tailFemale: "",
    length: "",
    lengthMale: "2.5-3.3 m",
    lengthFemale: "2.3-2.7 m",
    horns: "",
    gestation: "3.5 months",
    teats: "4 abdominal",
    teeth: 30,
    photos: [
      {
        id: 1,
        title: "Lion",
        description: "Male lion giving a lioness a 'love bite'.",
        imgURL: "../assets/images/animals/lion.jpg",
        active: true
      },
      {
        id: 2,
        title: "Lion",
        description: "Lion at Klopperfontein waterhole.",
        imgURL: "../assets/images/animals/lion-02.jpg",
        active: false
      },
      {
        id: 3,
        title: "Lion",
        description: "",
        imgURL: "../assets/images/animals/lion-03.jpg",
        active: false
      }
    ]
  },
  {
    id: 8,
    featured: true,
    slug: "hyaena",
    title: "Spotted Hyaena",
    latin: "Crocuta crocuta",
    order: "carnivora",
    suborder: "feliformia",
    superFamily: "",
    family: "hyaenidae",
    subFamily: "hyaeninae",
    tribe: "",
    collective: ["clan", "cackle"],
    weight: "",
    weightMale: "46-79 kg",
    weightFemale: "56-80 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "77-85 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "25 cm",
    tailMale: "",
    tailFemale: "",
    length: "120-180 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "3.5 months",
    teats: "2 abdominal",
    teeth: 34,
    photos: [
      {
        id: 1,
        title: "Hyaena",
        description: "",
        imgURL: "../assets/images/animals/hyaena.jpg",
        active: true
      },
      {
        id: 2,
        title: "Hyaena",
        description: "",
        imgURL: "../assets/images/animals/hyaena-02.jpg",
        active: false
      },
      {
        id: 3,
        title: "Hyaena",
        description: "",
        imgURL: "../assets/images/animals/hyaena-03.jpg",
        active: false
      }
    ]
  },
  {
    id: 9,
    featured: true,
    slug: "white-rhino",
    title: "White Rhino",
    latin: "Ceratotherium simum",
    order: "perissodactyla",
    suborder: "",
    superFamily: "",
    family: "rhinocerotidae",
    subFamily: "",
    tribe: "",
    collective: ["crash", "stubborness", "herd"],
    weight: "",
    weightMale: "2000-2300 kg",
    weightFemale: "1300-1600 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "180 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "100 cm",
    tailMale: "",
    tailFemale: "",
    length: "4.5-4.8 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "16 months",
    teats: "2 inguinal",
    teeth: 24,
    photos: [
      {
        id: 1,
        title: "White Rhino",
        description: "",
        imgURL: "../assets/images/animals/white-rhino-01.jpg",
        active: true
      }
    ]
  },
  {
    id: 10,
    featured: false,
    slug: "aardvark",
    title: "Aardvark",
    latin: "Orycteropus afer",
    order: "tubulidentata",
    suborder: "",
    superFamily: "",
    family: "orycteropodidae",
    subFamily: "",
    tribe: "",
    collective: [],
    weight: "40-65 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "61 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "45-60 cm",
    tailMale: "",
    tailFemale: "",
    length: "170-190 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "7 months",
    teats: "2 abdominal and 2 inguinal",
    teeth: 20,
    photos: []
  },
  {
    id: 11,
    featured: false,
    slug: "honey-badger",
    title: "Honey Badger",
    latin: "Mellivora capensis",
    order: "carnivora",
    suborder: "caniformia",
    superFamily: "",
    family: "mustelidae",
    subFamily: "mellivorinae",
    tribe: "",
    collective: ["crete", "colony", "company"],
    weight: "8-14.5 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "25-28 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "18-24 cm",
    tailMale: "",
    tailFemale: "",
    length: "90-100 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "180 days",
    teats: "4 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 12,
    featured: false,
    slug: "bushbuck",
    title: "Bushbuck",
    latin: "Tragelaphus scriptus",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "bovinae",
    tribe: "tragelaphini",
    collective: ["herd", "cluster", "tribe"],
    weight: "",
    weightMale: "48 kg",
    weightFemale: "30 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "",
    shoulderMale: "80 cm",
    shoulderFemale: "70 cm",
    tail: "20 cm",
    tailMale: "",
    tailFemale: "",
    length: "",
    lengthMale: "1.35-1.7m",
    lengthFemale: "1.3-1.5 m",
    horns: "males only",
    gestation: "180 days",
    teats: "4",
    teeth: 32,
    photos: []
  },
  {
    id: 13,
    featured: false,
    slug: "caracal",
    title: "Caracal",
    latin: "Caracal caracal",
    order: "carnivora",
    suborder: "feliformia",
    superFamily: "",
    family: "felidae",
    subFamily: "felinae",
    tribe: "",
    collective: [],
    weight: "",
    weightMale: "12-18 kg",
    weightFemale: "8-13 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "40-45 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "18-34 cm",
    tailMale: "",
    tailFemale: "",
    length: "70-117 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "79 days",
    teats: "6 abdominal",
    teeth: 30,
    photos: []
  },
  {
    id: 14,
    featured: false,
    slug: "african-wild-cat",
    title: "African Wild Cat",
    latin: "Felis silvestris lybica",
    order: "carnivora",
    suborder: "feliformia",
    superFamily: "",
    family: "felidae",
    subFamily: "felinae",
    tribe: "",
    collective: ["destruction"],
    weight: "",
    weightMale: "3.5-6 kg",
    weightFemale: "2.5-5.5 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "35 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "25-37 cm",
    tailMale: "",
    tailFemale: "",
    length: "82-100 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "65 days",
    teats: "8 abdominal",
    teeth: 30,
    photos: []
  },
  {
    id: 15,
    featured: false,
    slug: "african-civet",
    title: "African Civet",
    latin: "Civettictis civetta",
    order: "carnivora",
    suborder: "feliformia",
    superFamily: "",
    family: "viverridae",
    subFamily: "felinae",
    tribe: "",
    collective: ["destruction"],
    weight: "",
    weightMale: "9.5-13 kg",
    weightFemale: "9.7-18 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "40 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "42-50 cm",
    tailMale: "",
    tailFemale: "",
    length: "120-140 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "60-65 days",
    teats: "4 abdominal",
    teeth: 30,
    photos: []
  },
  {
    id: 16,
    featured: false,
    slug: "blue-duiker",
    title: "Blue Duiker",
    latin: "Cephalophus monticola",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "antilopinae",
    tribe: "cephalophini",
    collective: [],
    weight: "3.5-6 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "35 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "7-12 cm",
    tailMale: "",
    tailFemale: "",
    length: "65-85 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "both genders",
    gestation: "4-4.5 months",
    teats: "4 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 17,
    featured: false,
    slug: "common-duiker",
    title: "Common Duiker",
    latin: "Sylvicapra grimmia",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "antilopinae",
    tribe: "cephalophini",
    collective: [],
    weight: "18-21 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "50 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "12 cm",
    tailMale: "",
    tailFemale: "",
    length: "90-135 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "males only",
    gestation: "3 months",
    teats: "4 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 18,
    featured: false,
    slug: "red-duiker",
    title: "Red Duiker",
    latin: "Cephalophus natalensis",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "antilopinae",
    tribe: "cephalophini",
    collective: [],
    weight: "11-13 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "45 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "9-15 cm",
    tailMale: "",
    tailFemale: "",
    length: "80-110 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "both genders",
    gestation: "5.5-6.5 months",
    teats: "4 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 19,
    featured: false,
    slug: "eland",
    title: "Eland",
    latin: "Tragelaphus oryx",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "bovinae",
    tribe: "tragelaphini",
    collective: ["herd"],
    weight: "",
    weightMale: "700-900 kg",
    weightFemale: "450 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "",
    shoulderMale: "1.7 m",
    shoulderFemale: "1.5 m",
    tail: "60 cm",
    tailMale: "",
    tailFemale: "",
    length: "",
    lengthMale: "3-4.2 m",
    lengthFemale: "2.2-3.5 m",
    horns: "both genders",
    gestation: "8-9 months",
    teats: "4 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 20,
    featured: false,
    slug: "bat-eared-fox",
    title: "Bat-eared Fox",
    latin: "Otocyon megalotis",
    order: "carnivora",
    suborder: "caniformia",
    superFamily: "",
    family: "canidae",
    subFamily: "",
    tribe: "",
    collective: ["skulk", "earth", "lead"],
    weight: "3-5 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "30-38 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "23-34 cm",
    tailMale: "",
    tailFemale: "",
    length: "75-90 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "2-2.5 months",
    teats: "4 inguinal",
    teeth: "46-50",
    photos: []
  },
  {
    id: 21,
    featured: false,
    slug: "southern-lesser-galago",
    title: "Southern Lesser Galago",
    latin: "Galago moholi",
    order: "primates",
    suborder: "strepsirhini",
    superFamily: "lorisoidea",
    family: "galagidae",
    subFamily: "",
    tribe: "",
    collective: ["congress", "plot", "gathering"],
    weight: "100-240 g",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "15-28 cm",
    tailMale: "",
    tailFemale: "",
    length: "30-40 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "120 days",
    teats: "2 pectoral and 2 inguinal",
    teeth: 36,
    photos: []
  },
  {
    id: 22,
    featured: false,
    slug: "thick-tailed-galago",
    title: "Thick-tailed Galago",
    latin: "Galago crassicaudatus",
    order: "primates",
    suborder: "strepsirhini",
    superFamily: "lorisoidea",
    family: "galagidae",
    subFamily: "",
    tribe: "",
    collective: ["congress", "plot", "gathering"],
    weight: "0.8-1.5 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "30-50 cm",
    tailMale: "",
    tailFemale: "",
    length: "70-80 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "130 days",
    teats: "2 pectoral and 2 inguinal",
    teeth: 36,
    photos: []
  },
  {
    id: 23,
    featured: false,
    slug: "gemsbok",
    title: "Gemsbok",
    latin: "Oryx gazella",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "antilopinae",
    tribe: "hippotragini",
    collective: ["herd"],
    weight: "",
    weightMale: "240 kg",
    weightFemale: "210 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "120 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "46 cm",
    tailMale: "",
    tailFemale: "",
    length: "1.9-2.15 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "both genders",
    gestation: "9 months",
    teats: "4 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 24,
    featured: false,
    slug: "large-spotted-genet",
    title: "Large-spotted Genet",
    latin: "Genetta tigrina",
    order: "carnivora",
    suborder: "feliformia",
    superFamily: "",
    family: "viverridae",
    subFamily: "",
    tribe: "",
    collective: [],
    weight: "1.5-3.2 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "18-22 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "40-50 cm",
    tailMale: "",
    tailFemale: "",
    length: "85-110 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "70 days",
    teats: "4 abdominal",
    teeth: 40,
    photos: []
  },
  {
    id: 25,
    featured: false,
    slug: "small-spotted-genet",
    title: "Small-spotted Genet",
    latin: "Genetta genetta",
    order: "carnivora",
    suborder: "feliformia",
    superFamily: "",
    family: "viverridae",
    subFamily: "",
    tribe: "",
    collective: [],
    weight: "1.5-2.5 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "18-20 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "40-50 cm",
    tailMale: "",
    tailFemale: "",
    length: "85-100 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "70 days",
    teats: "4 abdominal",
    teeth: 40,
    photos: []
  },
  {
    id: 26,
    featured: false,
    slug: "lichtensteins-hartebeest",
    title: "Lichtenstein's Hartebeest",
    latin: "Alcelaphus lichtensteinii",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "antilopinae",
    tribe: "alcelaphini",
    collective: [],
    weight: "",
    weightMale: "130-160 kg",
    weightFemale: "100-150 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "125 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "48 cm",
    tailMale: "",
    tailFemale: "",
    length: "2-2.5 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "both genders",
    gestation: "240 days",
    teats: "2 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 27,
    featured: false,
    slug: "red-hartebeest",
    title: "Red Hartebeest",
    latin: "Alcelaphus buselaphus",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "antilopinae",
    tribe: "alcelaphini",
    collective: [],
    weight: "",
    weightMale: "150 kg",
    weightFemale: "120 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "125 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "47 cm",
    tailMale: "",
    tailFemale: "",
    length: "2.3 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "both genders",
    gestation: "240 days",
    teats: "2 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 28,
    featured: false,
    slug: "hippopotamus",
    title: "Hippopotamus",
    latin: "Hippopotamus amphibius",
    order: "whippomorpha",
    suborder: "ancodonta",
    superFamily: "",
    family: "hippopotamidae",
    subFamily: "",
    tribe: "",
    collective: ["bloat", "herd", "raft", "thunder"],
    weight: "",
    weightMale: "1000-2000 kg",
    weightFemale: "1000-1700 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "1.3-1.7 m",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "30-50 cm",
    tailMale: "",
    tailFemale: "",
    length: "3.4-4.5 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "7.5-8.5 months",
    teats: "2 inguinal",
    teeth: "36-40",
    photos: []
  },
  {
    id: 29,
    featured: false,
    slug: "brown-hyaena",
    title: "Brown Hyaena",
    latin: "Parahyaena brunnea",
    order: "carnivora",
    suborder: "feliformia",
    superFamily: "hyaeninae",
    family: "hyaenidae",
    subFamily: "",
    tribe: "",
    collective: ["clan", "cackle"],
    weight: "",
    weightMale: "35-55 kg",
    weightFemale: "28-48 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "80 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "17-30 cm",
    tailMale: "",
    tailFemale: "",
    length: "130-160 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "90 days",
    teats: "4 abdominal",
    teeth: 34,
    photos: []
  },
  {
    id: 30,
    featured: false,
    slug: "rock-hyrax",
    title: "Rock Hyrax",
    latin: "Procavia capensis",
    order: "hyracoidea",
    suborder: "",
    superFamily: "",
    family: "procaviidae",
    subFamily: "",
    tribe: "",
    collective: ["bury", "colony"],
    weight: "",
    weightMale: "3.2-4.7 kg",
    weightFemale: "2.5-4.2 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "15-20 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "",
    tailMale: "",
    tailFemale: "",
    length: "38-60 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "210 days",
    teats: "2 pectoral and 4 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 31,
    featured: false,
    slug: "impala",
    title: "Impala",
    latin: "Aepyceros melampus",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "antilopinae",
    tribe: "aepycerotini",
    collective: ["herd"],
    weight: "",
    weightMale: "45-75 kg",
    weightFemale: "32-50 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "70-90 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "28 cm",
    tailMale: "",
    tailFemale: "",
    length: "1.4-1.7 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "only males",
    gestation: "6.5 months",
    teats: "4 inguinal",
    teeth: 32,
    photos: [
      {
        id: 1,
        title: "Impala",
        description: "",
        imgURL: "../assets/images/animals/impala-01.jpg",
        active: true
      }
    ]
  },
  {
    id: 32,
    featured: false,
    slug: "black-backed-jackal",
    title: "Black-backed Jackal",
    latin: "Canis mesomelas",
    order: "carnivora",
    suborder: "caniformia",
    superFamily: "",
    family: "canidae",
    subFamily: "",
    tribe: "",
    collective: ["skulk", "pack"],
    weight: "6-12 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "32-48 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "28-37 cm",
    tailMale: "",
    tailFemale: "",
    length: "70-125 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "2 months",
    teats: "6-8",
    teeth: 42,
    photos: []
  },
  {
    id: 33,
    featured: false,
    slug: "klipspringer",
    title: "Klipspringer",
    latin: "Oreotragus oreotragus",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "antilopinae",
    tribe: "oreotragini",
    collective: [],
    weight: "",
    weightMale: "9-12 kg",
    weightFemale: "11-13 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "50-55 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "8 cm",
    tailMale: "",
    tailFemale: "",
    length: "80-100 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "only males",
    gestation: "5.5-6.5 months",
    teats: "4 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 34,
    featured: false,
    slug: "greater-kudu",
    title: "Greater Kudu",
    latin: "Tragelaphus strepsiceros",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "bovinae",
    tribe: "tragelaphini",
    collective: ["herd"],
    weight: "",
    weightMale: "190-400 kg",
    weightFemale: "120-200 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "",
    shoulderMale: "1.4-1.55 m",
    shoulderFemale: "1.2-1.35 m",
    tail: "43 cm",
    tailMale: "",
    tailFemale: "",
    length: "2.3-2.9 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "only males",
    gestation: "9 months",
    teats: "4 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 35,
    featured: false,
    slug: "leopard",
    title: "Leopard",
    latin: "Panthera pardus",
    order: "carnivora",
    suborder: "feliformia",
    superFamily: "",
    family: "felidae",
    subFamily: "pantherinae",
    tribe: "tragelaphini",
    collective: ["leap", "lepe"],
    weight: "",
    weightMale: "20-90 kg",
    weightFemale: "17-60 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "70 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "68-110 cm",
    tailMale: "",
    tailFemale: "",
    length: "1.6-2 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "3 months",
    teats: "4 abdominal",
    teeth: 30,
    photos: []
  },
  {
    id: 36,
    featured: false,
    slug: "meerkat",
    title: "Meerkat",
    latin: "Suricata suricatta",
    order: "carnivora",
    suborder: "feliformia",
    superFamily: "",
    family: "herpestidae",
    subFamily: "",
    tribe: "",
    collective: ["clan", "gang", "mob"],
    weight: "620-950 g",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "12 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "19-24 cm",
    tailMale: "",
    tailFemale: "",
    length: "45-55 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "60-70 days",
    teats: "6 abdominal",
    teeth: 36,
    photos: []
  },
  {
    id: 37,
    featured: false,
    slug: "banded-mongoose",
    title: "Banded Mongoose",
    latin: "Mungos mungo",
    order: "carnivora",
    suborder: "feliformia",
    superFamily: "",
    family: "herpestidae",
    subFamily: "",
    tribe: "",
    collective: ["business", "family", "pack"],
    weight: "1-1.5 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "18-20 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "18-25 cm",
    tailMale: "",
    tailFemale: "",
    length: "50-65 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "60 days",
    teats: "6 abdominal",
    teeth: 36,
    photos: []
  },
  {
    id: 38,
    featured: false,
    slug: "dwarf-mongoose",
    title: "Dwarf Mongoose",
    latin: "Helogale parvula",
    order: "carnivora",
    suborder: "feliformia",
    superFamily: "",
    family: "herpestidae",
    subFamily: "",
    tribe: "",
    collective: ["business", "family"],
    weight: "210-350 g",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "7.5 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "24-20 cm",
    tailMale: "",
    tailFemale: "",
    length: "35-40 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "8 weeks",
    teats: "4 abdominal",
    teeth: 36,
    photos: []
  },
  {
    id: 39,
    featured: false,
    slug: "slender-mongoose",
    title: "Slender Mongoose",
    latin: "Galerella sanguinea",
    order: "carnivora",
    suborder: "feliformia",
    superFamily: "",
    family: "herpestidae",
    subFamily: "",
    tribe: "",
    collective: ["business"],
    weight: "",
    weightMale: "500-800 g",
    weightFemale: "370-560 g",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "10 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "23-30 cm",
    tailMale: "",
    tailFemale: "",
    length: "50-65 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "60 days",
    teats: "4 abdominal",
    teeth: 38,
    photos: []
  },
  {
    id: 40,
    featured: false,
    slug: "yellow-mongoose",
    title: "Yellow Mongoose",
    latin: "Cynictis penicillata",
    order: "carnivora",
    suborder: "feliformia",
    superFamily: "",
    family: "herpestidae",
    subFamily: "",
    tribe: "",
    collective: ["business"],
    weight: "450-900 g",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "16-18 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "18-25 cm",
    tailMale: "",
    tailFemale: "",
    length: "40-60 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "8 weeks",
    teats: "6 abdominal",
    teeth: 40,
    photos: []
  },
  {
    id: 41,
    featured: false,
    slug: "vervet-monkey",
    title: "Vervet Monkey",
    latin: "Cercopithecus pygerythrus",
    order: "primata",
    suborder: "haplorhini",
    superFamily: "cercopithecoidea",
    family: "cercopithecidae",
    subFamily: "",
    tribe: "",
    collective: ["shrewdness", "troop", "cartload", "tribe"],
    weight: "",
    weightMale: "3.8-8 kg",
    weightFemale: "3.4-5.2 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "",
    shoulderMale: "31 cm",
    shoulderFemale: "26 cm",
    tail: "",
    tailMale: "60-75 cm",
    tailFemale: "48-65 cm",
    length: "",
    lengthMale: "100-130 cm",
    lengthFemale: "95-110 cm",
    horns: "",
    gestation: "5-5.5 months",
    teats: "2 pectoral",
    teeth: 32,
    photos: []
  },
  {
    id: 42,
    featured: false,
    slug: "nyala",
    title: "Nyala",
    latin: "Tragelaphus angasii",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "bovinae",
    tribe: "tragelaphini",
    collective: ["herd"],
    weight: "",
    weightMale: "90-120 kg",
    weightFemale: "55-68 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "",
    shoulderMale: "112 cm",
    shoulderFemale: "95 cm",
    tail: "",
    tailMale: "43 cm",
    tailFemale: "36 cm",
    length: "",
    lengthMale: "2.1 m",
    lengthFemale: "1.8 m",
    horns: "only males",
    gestation: "7 months",
    teats: "4 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 43,
    featured: false,
    slug: "cape-clawless-otter",
    title: "Cape Clawless Otter",
    latin: "Aonyx capensis",
    order: "carnivora",
    suborder: "caniformia",
    superFamily: "",
    family: "mustelidae",
    subFamily: "lutrinae",
    tribe: "",
    collective: ["family", "romp", "raft"],
    weight: "12-18 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "35 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "40 cm",
    tailMale: "",
    tailFemale: "",
    length: "1.1-1.8 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "9 weeks",
    teats: "4 abdominal",
    teeth: 36,
    photos: []
  },
  {
    id: 44,
    featured: false,
    slug: "ground-pangolin",
    title: "Ground Pangolin",
    latin: "Manis temminckii",
    order: "pholidota",
    suborder: "",
    superFamily: "",
    family: "manidae",
    subFamily: "",
    tribe: "",
    collective: [],
    weight: "4.5-18 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "30-50 cm",
    tailMale: "",
    tailFemale: "",
    length: "70-125 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "4.5 months",
    teats: "4 pectoral",
    teeth: 0,
    photos: []
  },
  {
    id: 45,
    featured: false,
    slug: "striped-polecat",
    title: "Striped Polecat",
    latin: "Ictonyx striatus",
    order: "carnivora",
    suborder: "caniformia",
    superFamily: "",
    family: "mustelidae",
    subFamily: "mustelinae",
    tribe: "",
    collective: ["chime of polecats", "surfeit of skunks"],
    weight: "0.5-1.4 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "10-15 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "26 cm",
    tailMale: "",
    tailFemale: "",
    length: "57-67 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "5-6 weeks",
    teats: "2 abdominal and 2 inguinal",
    teeth: 34,
    photos: []
  },
  {
    id: 46,
    featured: false,
    slug: "common-reedbuck",
    title: "Common Reedbuck",
    latin: "Redunca arundinum",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "antelopinae",
    tribe: "reduncini",
    collective: ["herd"],
    weight: "",
    weightMale: "43-68 kg",
    weightFemale: "32-50 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "80-95 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "25 cm",
    tailMale: "",
    tailFemale: "",
    length: "",
    lengthMale: "1.5-1.8 m",
    lengthFemale: "1.4-1.7 m",
    horns: "only males",
    gestation: "7.5 months",
    teats: "4 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 47,
    featured: false,
    slug: "black-rhinoceros",
    title: "Black Rhinoceros",
    latin: "Diceros bicornis",
    order: "perissodactyla",
    suborder: "",
    superFamily: "",
    family: "rhinocerotidae",
    subFamily: "",
    tribe: "",
    collective: ["crash", "stuborness", "herd"],
    weight: "750-1000 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "140-165 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "70 cm",
    tailMale: "",
    tailFemale: "",
    length: "3.5-4.3 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "15 months",
    teats: "2 inguinal",
    teeth: "26-28",
    photos: []
  },
  {
    id: 48,
    featured: false,
    slug: "roan-antelope",
    title: "Roan Antelope",
    latin: "Hippotragus equinus",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "antilopinae",
    tribe: "hippotragini",
    collective: ["herd", "cluster", "tribe"],
    weight: "",
    weightMale: "260-300 kg",
    weightFemale: "220-260 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "",
    shoulderMale: "142 cm",
    shoulderFemale: "135 cm",
    tail: "54 cm",
    tailMale: "",
    tailFemale: "",
    length: "2.2-2.9 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "both genders",
    gestation: "9-9.5 months",
    teats: "4 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 49,
    featured: false,
    slug: "sable-antelope",
    title: "Sable Antelope",
    latin: "Hippotragus niger",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "antilopinae",
    tribe: "hippotragini",
    collective: ["herd", "cluster", "tribe"],
    weight: "185-270 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "130 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "55 cm",
    tailMale: "",
    tailFemale: "",
    length: "2.3-2.6 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "both genders",
    gestation: "9-9.5 months",
    teats: "4 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 50,
    featured: false,
    slug: "serval",
    title: "Serval",
    latin: "Leptailurus serval",
    order: "carnivora",
    suborder: "feliformia",
    superFamily: "",
    family: "felidae",
    subFamily: "felinae",
    tribe: "hippotragini",
    collective: ["destruction"],
    weight: "",
    weightMale: "9-13 kg",
    weightFemale: "8-12 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "60 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "25-38 cm",
    tailMale: "",
    tailFemale: "",
    length: "95-120 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "2.5 months",
    teats: "4 abdominal and 2 inguinal",
    teeth: 30,
    photos: []
  },
  {
    id: 51,
    featured: false,
    slug: "springbok",
    title: "Springbok",
    latin: "Antidorcas marsupialis",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "antilopinae",
    tribe: "antilopini",
    collective: ["herd", "cluster", "tribe"],
    weight: "",
    weightMale: "32-55 kg",
    weightFemale: "26-40 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "75 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "25 cm",
    tailMale: "",
    tailFemale: "",
    length: "1.2-1.3 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "both genders",
    gestation: "6.5-7 months",
    teats: "2 inguinal, rarely 4",
    teeth: 28,
    photos: []
  },
  {
    id: 52,
    featured: false,
    slug: "steenbok",
    title: "Steenbok",
    latin: "Raphicerus campestris",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "antilopinae",
    tribe: "antilopini",
    collective: ["herd", "cluster", "tribe"],
    weight: "9-13 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "50 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "5 cm",
    tailMale: "",
    tailFemale: "",
    length: "75-92 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "only males",
    gestation: "5.5-6 months",
    teats: "4 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 53,
    featured: false,
    slug: "suni",
    title: "Suni",
    latin: "Neotragus moschatus",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "neotraginae",
    tribe: "neotragini",
    collective: ["herd", "cluster", "tribe"],
    weight: "4.7 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "35 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "9-11 cm",
    tailMale: "",
    tailFemale: "",
    length: "66-75 cm",
    lengthMale: "",
    lengthFemale: "",
    horns: "only males",
    gestation: "5-7 months",
    teats: "4 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 54,
    featured: false,
    slug: "tsessebe",
    title: "Tsessebe",
    latin: "Damaliscus lunatus",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "antilopinae",
    tribe: "alcelaphini",
    collective: ["herd", "cluster", "tribe"],
    weight: "",
    weightMale: "140 kg",
    weightFemale: "126 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "125 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "43 cm",
    tailMale: "",
    tailFemale: "",
    length: "1.9-2.3 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "both genders",
    gestation: "8 months",
    teats: "2 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 55,
    featured: false,
    slug: "common-waterbuck",
    title: "Common Waterbuck",
    latin: "Kobus ellipsiprymnus",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "antilopinae",
    tribe: "reduncini",
    collective: ["herd", "cluster", "tribe"],
    weight: "200-270 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "1.1-1.6 m",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "35 cm",
    tailMale: "",
    tailFemale: "",
    length: "2.1-2.7 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "only males",
    gestation: "8-8.5 months",
    teats: "4 inguinal",
    teeth: 32,
    photos: []
  },
  {
    id: 56,
    featured: false,
    slug: "common-warthog",
    title: "Common Warthog",
    latin: "Phacochoerus africanus",
    order: "suiformes",
    suborder: "",
    superFamily: "",
    family: "suidae",
    subFamily: "phacochoerinae",
    tribe: "",
    collective: ["sounder"],
    weight: "",
    weightMale: "60-105 kg",
    weightFemale: "45-70 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "",
    shoulderMale: "70 cm",
    shoulderFemale: "60 cm",
    tail: "45 cm",
    tailMale: "",
    tailFemale: "",
    length: "1.3-1.5 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "only males",
    gestation: "5.5-6 months",
    teats: "2 inguinal and 2 abdominal",
    teeth: "32-34",
    photos: []
  },
  {
    id: 57,
    featured: false,
    slug: "black-wildebeest",
    title: "Black Wildebeest",
    latin: "Connochaetes gnou",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "antilopinae",
    tribe: "alcelaphini",
    collective: ["implausibility", "herd"],
    weight: "100-180 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "1.2 m",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "80-100 cm",
    tailMale: "",
    tailFemale: "",
    length: "2.6-3.2 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "both genders",
    gestation: "8-8.5 months",
    teats: "2 inguinal",
    teeth: 30,
    photos: []
  },
  {
    id: 58,
    featured: false,
    slug: "blue-wildebeest",
    title: "Blue Wildebeest",
    latin: "Connochaetes taurinus",
    order: "ruminantia",
    suborder: "",
    superFamily: "",
    family: "bovidae",
    subFamily: "antilopinae",
    tribe: "alcelaphini",
    collective: ["implausibility", "herd"],
    weight: "",
    weightMale: "250 kg",
    weightFemale: "180 kg",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "",
    shoulderMale: "1.45 m",
    shoulderFemale: "1.3 m",
    tail: "50-100 cm",
    tailMale: "",
    tailFemale: "",
    length: "2.4-3.3 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "both genders",
    gestation: "8-8.5 months",
    teats: "2 inguinal",
    teeth: 30,
    photos: []
  },
  {
    id: 59,
    featured: false,
    slug: "cape-mountain-zebra",
    title: "Cape Mountain Zebra",
    latin: "Equus zebra zebra",
    order: "perissodactyla",
    suborder: "",
    superFamily: "",
    family: "equidae",
    subFamily: "",
    tribe: "",
    collective: ["dazzle", "zeal", "cohort"],
    weight: "250-260 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "130 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "40 cm",
    tailMale: "",
    tailFemale: "",
    length: "2.7 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "12 months",
    teats: "2 inguinal",
    teeth: "mare: 36, stallion: 40",
    photos: []
  },
  {
    id: 60,
    featured: false,
    slug: "plains-zebra",
    title: "Plains Zebra",
    latin: "Equus quagga",
    order: "perissodactyla",
    suborder: "",
    superFamily: "",
    family: "equidae",
    subFamily: "",
    tribe: "",
    collective: ["dazzle", "zeal", "cohort"],
    weight: "290-340 kg",
    weightMale: "",
    weightFemale: "",
    height: "",
    heightMale: "",
    heightFemale: "",
    shoulder: "130 cm",
    shoulderMale: "",
    shoulderFemale: "",
    tail: "45-56 cm",
    tailMale: "",
    tailFemale: "",
    length: "2.3-3 m",
    lengthMale: "",
    lengthFemale: "",
    horns: "",
    gestation: "12 months",
    teats: "2 inguinal",
    teeth: "mare: 36, stallion: 40",
    photos: []
  }
];
